service: company-registration-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  timeout: 5
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table:Companies

functions:
  registerCompany:
    handler: src/registerCompany.handler
    description: Lambda that registers a company in DynamoDB
    events:
      - http:
          path: registrations
          method: post
          cors: true

resources:
  Resources:
    Companies:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Companies
        AttributeDefinitions:
          - AttributeName: cuit
            AttributeType: S
        KeySchema:
          - AttributeName: cuit
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
